### ISSUE TITLE
Show whether event was trigger by WebUI vs. APIv2 vs. APIv1

### ISSUE THREAD

**Issue by lgierth** [dnsimple/strillone#2]
We want to be able to "blame" people who use APIv1 or (even worse) the Web UI to make DNS changes.

**Comment by weppos** [comment]
We currently don't pass that information to the events, therefore this app can't really display it.

API v1 doesn't support webhooks at all, but because the way we structured the old API it's in fact possible for an API v1 request to trigger an activity, and hence an event in API v2 (if you listen to it).

I'll open an internal feature request to see how feasible it is to pass the request type context into the events.

**Comment by weppos** [comment]
I opened an internal ticket. I am closing this one as unfortunately it's not actionable right now, since that information is not in the event payload at all.

**Comment by lgierth** [comment]
Hehe yeah I understand :) The general UI vs. API distinction would already help a ton :)
